---
all:
  children:
    k8s:
      vars:
        ansible_user: k8sadmin
        ansible_ssh_private_key_file: ~/.ssh/k8s_portfolio
        ansible_python_interpreter: /usr/bin/python3
      children:
        controlplane:
          hosts:
            k8s-controlplane:
              ansible_host: 4.168.236.114
        workers:
          hosts:
            k8s-worker:
              ansible_host: 102.133.225.72
